### ISSUE TITLE
linkify example?

### ISSUE THREAD

**Issue by mbodge** [obipawan/react-native-hyperlink#10]
Hey there, thanks for making this library. I'm looking to do some twitter parsing and want to add a @name recognizer to add a link  to it. I saw ou support linkify-it but I can't figure out what kind of object i'm supposed to pass. Any simple example you can provide would be super helpful. Thanks.

**Comment by obipawan** [comment]
Hey @mbodge 

This is an example from the [linkify-it](https://github.com/markdown-it/linkify-it#example-2-add-twitter-mentions-handler)'s repo 


```javascript
linkify.add('@', {
  validate: function (text, pos, self) {
    var tail = text.slice(pos);
    if (!self.re.twitter) {
      self.re.twitter =  new RegExp(
        '^([a-zA-Z0-9_]){1,15}(?!_)(?=$|' + self.re.src_ZPCc + ')'
      );
    }
    if (self.re.twitter.test(tail)) {
      // Linkifier allows punctuation chars before prefix,
      // but we additionally disable `@` ("@@mention" is invalid)
      if (pos >= 2 && tail[pos - 2] === '@') {
        return false;
      }
      return tail.match(self.re.twitter)[0].length;
    }
    return 0;
  },
  normalize: function (match) {
    match.url = 'https://twitter.com/' + match.url.replace(/^@/, '');
  }
});
```

so basically your component should look something like

```javascript
import React, { Component } from 'react'
import { Text } from 'react-native'
import Hyperlink from 'react-native-hyperlink'
const linkify = require('linkify-it')()

linkify.add('@', { ... }) // add your custom handler here

export default () =>
<Hyperlink
    linkify={ linkify }
    onPress={ ... }
    ...
>
    <Text>twitter handles like @name should be parsable</Text>
</Hyperlink>
```

**Comment by mbodge** [comment]
You. Are. The. Best.

Thanks so much for this.

**Comment by codal-mpawar** [comment]
@obipawan @mbodge Can you please help me how can i render this 
@[Manthan](1fca0e7d-92c3-40c4-9c9c-be84124ec9a8) dads asd @[Manthan](072ac78f-ae12-4049-b721-846092acb8f5)

We need to add space allow in that name 
and we need id tap on the name.
