### ISSUE TITLE
[IOS] No component found for view with name "RCTVirtualText"

### ISSUE THREAD

**Issue by cherniv** [obipawan/react-native-hyperlink#12]
Hey after RN upgrading to version 0.44, hyperlink stopped working. It crashes with this error:

> [error][tid:com.facebook.react.ShadowQueue][RCTUIManager.m:1011] No component found for view with name "RCTVirtualText"

The code is:
```
<Hyperlink onPress={ url => alert(url) }>
	<Text>http://blabla.com</Text>
</Hyperlink>

```
The interesting part is that this is working fine:
```
<Hyperlink onPress={ url => alert(url) }>
	<Text>hello</Text>
</Hyperlink>
```

Any ideas?

![image](https://cloud.githubusercontent.com/assets/3829914/25838988/60657626-349e-11e7-8335-c496f147c922.png)

**Comment by obipawan** [comment]
Hey @cherniv!
Thanks for reporting. I haven't tried this out on 0.44 yet, so I'm not really sure what could be causing this. Will take a look at this later tonight :)

**Comment by obipawan** [comment]
@cherniv I tried this out with a fresh project on `0.44` running on iOS and I didn't observe this crash. I tried looking through the error in the react-native repo and it seems like this is a java native file. Seems odd that a bundle for iOS is looking for a native module in android. Perhaps you have your own npm script to run android | iOS bundles separately and that got mixed up? 
Either way, you could try to clean the `node_modules` (rm) and then reinstall the dependencies and see if that works? LMK

**Comment by obipawan** [comment]
also here's a result for a text search `RCTVirtualText` https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=RCTVirtualText&type=`

**Comment by cherniv** [comment]
Ok, i downgraded my RN version to 0.43.4 and now it works. Thanks
