### ISSUE TITLE
onLongPress not working on Android

### ISSUE THREAD

**Issue by jimmyc1987** [obipawan/react-native-hyperlink#14]
Works fine on iOS.

Nice work btw. Thanks.

**Comment by obipawan** [comment]
Hey @jimmyc1987

Thanks for reporting and apologies for the delay :)

I just tried `onLongPress` on my android device and seems to be working. Could it be that your `Text` or any `View` component has a small tappable area?

Please feel free to drop in some code where you think this prop fails

Glad you like it :)

**Comment by obipawan** [comment]
ping!

**Comment by obipawan** [comment]
closing as abandoned.
