### ISSUE TITLE
Only works with https://

### ISSUE THREAD

**Issue by jose920405** [obipawan/react-native-hyperlink#17]
when I try to support pages with `http:` or simply with `www.`.

Example

http://www.whatever.com
www.whatever.com

Does not works

I have used

```
inkDefs = {[
     {
         regex: /(www|http:|https:)+[^\s]+[\w]/g,
     }
]}
```

and now if it detects them. But when I press this links `www.whatever.com`, they do not work. I'm not sure is this is a android requirement, but would be good know the best way for fix it, because in my case i can't guaranteeing `https` to `http` in all links.

I have tried adding

```
 onPress: (orig, text, url) => {
      // I change url to orig, because url come undefined for me.
      HyperlinkedText._openWebUrl(orig);
}
```

but it does not work either

**Comment by obipawan** [comment]
hey @jose920405 

Not sure if I get you. Are you saying that the `http` protocol isn't working for you? It shouldn't be the case. Can you share your jsx with the Hyperlink component? 

For an action on clicking, you need to either provide a `onPress` function prop or `linkDefault={ true }` for the platform to take care of linking

**Comment by obipawan** [comment]
ping! :)

**Comment by obipawan** [comment]
@jose920405 I'm closing this issue. Please feel free to write back if you still have this issue. Thanks
