### ISSUE TITLE
How to remove auto detect link?

### ISSUE THREAD

**Issue by ngocht143** [obipawan/react-native-hyperlink#19]
Hi @obipawan, i have an issue when using your lib that i want to display a text 
'Saya telah membaca dan menyetujui **ketentuan penggunaan** cinobile.com' and i just want to use hyperlink for the text 'ketentuan penggunaan' only. But when using your lib, it detected both the url 'cinobile.com'. How to remove auto detect link? Thanks in advance

**Comment by ngocht143** [comment]
Here is my code:
`<Hyperlink
                            linkStyle={{ color: '#074e8e', textDecorationLine: 'underline' }}
                            linkText={url => url === 'https://google.com' ? 'ketentuan penggunaan' : 'cinobile.com'}
                            onPress={() => { alert('Blabla') }}>
                            <Text style={{ marginTop: 20 }}>
                                Saya telah membaca dan menyetujui https://google.com cinobile.com
                            </Text>
                        </Hyperlink>`

**Comment by obipawan** [comment]
hey @ngocht143 
Thanks for using hyperlink :)

This library uses [linkify-it](https://github.com/markdown-it/linkify-it) to identify and parse urls. 

You'll need to play around with the linkifiy-it object itself and pass that as a prop to `Hyperlink`.
Something like so

```javascript
import React, { Component } from 'react'
import { Text } from 'react-native'
import Hyperlink from 'react-native-hyperlink'
const linkify = require('linkify-it')()

linkify.add('ketentuan penggunaan', { ... }) // custom handler
linkify.add('cinobile.com', { ... }) // custom handler

export default () =>
<Hyperlink
    linkify={ linkify } // pass the linkify object as prop
    onPress={ ... }
    ...
>
    <Text>your text here</Text>
</Hyperlink>
```

Check out the [Linkify-it](https://github.com/markdown-it/linkify-it) library for more details. Let me know if you still have any trouble.

**Comment by ngocht143** [comment]
Hi @obipawan, I'm trying to custom linkify like this:
const linkify = require('linkify-it')()
linkify.add('http:', null) // custom handler
and use in Hyperlink:
`<Hyperlink
                            linkify={linkify}
                            linkStyle={{ color: '#074e8e', textDecorationLine: 'underline' }}
                            linkText={url => url === 'https://google.com' ? 'ketentuan penggunaan' : ''}
                            onPress={() => { alert('Blabla') }}>
                            <Text style={{marginTop: 20}}>
                                Saya telah membaca dan menyetujui ketentuan penggunaan <Text>cinobile.com</Text>
                            </Text>
                        </Hyperlink>`

but it disable all hyperlink :( I'm newbie, please tell me what i have to do to custom linkify? Thanks in advance

**Comment by obipawan** [comment]
Hey @ngocht143 

adding `linkify.add('http:', null)` will disable all http links. If you want to add `ketentuan penggunaa` as a linkable text - you'll have to add this

```javascript
linkify.add('ketentuan penggunaan', { validate: () => 1 })
```

Also, I'm a little confused with what you want to achieve, do you want to replace a matched text with something else? or do you want to be able to match plain text like `ketentuan penggunaan`?

Apologies for the delay - I was on my vacation :)

**Comment by ngocht143** [comment]
Good morning @obipawan 
Here is what i want: [http://prntscr.com/hw86ye](url)
But here is what i got: [http://prntscr.com/hw88ai](url)
I'm expecting to listen onPress at 'ketentuan penggunaan' to go to policy screen (not go to web link), and the 'chodocu.com' is plain text, not hyperlink.

Thank for your support :)
