### ISSUE TITLE
Background color change on long press

### ISSUE THREAD

**Issue by tfsjohan** [obipawan/react-native-hyperlink#21]
If I long press anywhere on a text wrapped by Hyperlink, the background turns gray like a TouchableHighlight. 

Can this behavior be turned off?

**Comment by lequetur** [comment]
I have this issue but only on iOS.

**Comment by novakben** [comment]
Same here

**Comment by obipawan** [comment]
This should be fixed with [v0.0.13](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.13)

**Comment by Pauline-dcs** [comment]
HI @obipawan :) I have this issue again with the v0.0.19 and can't find a way to remove this grey highlight on long press. Do you have any solution?
