### ISSUE TITLE
Color of normal text overrides link style

### ISSUE THREAD

**Issue by ssg-luke** [obipawan/react-native-hyperlink#25]
I have run into an issue while using this module with the child having a defined color. At the moment I have the ```<Hyperlink>``` component wrapping a single ```<Text>``` component. The ```<Hyperlink>``` component has the ```linkStyle``` prop defined with color: "blue". The ```<Text>``` component also has its color set on the ```style``` prop to some offshade of black. However the resulting text ends up being entirely in the ```<Text>``` components color. The color from the ```linkStyle``` prop is lost. Hope someone can help

**Comment by ssg-luke** [comment]
Oh never mind I just removed the <Text> component and instead defined my text style on the <Hyperlink> component. Works fine.

**Comment by ssg-luke** [comment]
Sorry had to re-open this. I had to re-wrap the text in the ```<Text>``` component otherwise I would occasionally see errors about RawText needing to be wrapped in the ```<Text>``` component. After doing so I have noticed that it works perfectly fine on iOS but ```linkStyle``` does not work on Android only.

**Comment by obipawan** [comment]
Thanks for reporting and using Hyperlink @ssg-luke :)
What's the RN version you're on?
Also, Hyperlink does not handle raw text on its own, it works on `Text` components nested within Hyperlink

**Comment by ssg-luke** [comment]
I'm using RN 0.48.3

**Comment by rcarvalho** [comment]
I have a similar issue, except I want to give more information here. My block of text has multiple hyperlinks inside of it. Only the first hyperlink is not colored correctly. All subsequent hyperlinks have the proper styling. The issue only happens on Android; not iOS.

**Comment by obipawan** [comment]
Apologies for the delay guys.

I've been trying to reproduce this on android and I'm unable to. @rcarvalho @ssg-luke could you please share a minimal snippet of the problem?

I've tried @ssg-luke's sample and that seems to work alright. I'm probably missing something.

**Comment by obipawan** [comment]
closing as abandoned.

**Comment by 3DJakob** [comment]
> I have a similar issue, except I want to give more information here. My block of text has multiple hyperlinks inside of it. Only the first hyperlink is not colored correctly. All subsequent hyperlinks have the proper styling. The issue only happens on Android; not iOS.

I have this issue too on iOS. However I only when using styled-components. I solved this by adding `style={{ color: '#fff' }}` to the styled component instead of using the standard style-component definition. Very strange, I presume it has something to do with the styling overriding one another.
