### ISSUE TITLE
How to detect multiple links and get perticular link which has been clicked. 

### ISSUE THREAD

**Issue by VishalKumar2016** [obipawan/react-native-hyperlink#26]
Hi , i have an issue I am getting text from server and I don't know how many link the text can have but I want all links clickable and blue and want to get particular link which has been clicked when user click any link from multiple links text.
Please guide me how I can achieve this? Thanks in advance.

**Comment by ChristianTucker** [comment]
This isn't a direct answer to your question, but if you're obtaining data from a server, perhaps markdown would better suit your needs.

https://github.com/lwansbrough/react-native-markdown
https://github.com/CharlesMangwa/react-native-simple-markdown/tree/master

**Comment by obipawan** [comment]
react-native-hyperlink should be able to solve your problem

> I am getting text from server and I don't know how many link the text can have but I want all links clickable

wrap all the response you get from the server inside a `Text` component and that inside the `Hyperlink`
>  I want all links clickable and blue

All hyperlinks are automatically clickable when you provide the `onPress` prop to Hyperlink. For the styling, you can use `linkStyle` prop
> want to get particular link which has been clicked when user click any link from multiple links text

The `onPress` gives you the text when clicked

A simple example for this
```javscript
import Hyperlink from 'react-native-hyperlink
import { Text } from 'react-native'

export default () => {
    const textFromResponse = ... // get your text from the server
    return (
        <Hyperlink
              onPress={ url => alert('clicked url is -> ' + url) } // add your custom logic to handle clicks
              linkStyle={ { color: 'blue' } } // your custom styling for the links
        >
              <Text>{ textFromResponse }</Text>
        </Hyperlink
    )
}
```

**Comment by VishalKumar2016** [comment]
Thanks @obipawan
