### ISSUE TITLE
componentWillRecieveProps deprecation warning for react 16.3.1

### ISSUE THREAD

**Issue by timt** [obipawan/react-native-hyperlink#27]
componentWillReceiveProps is now deprecated in React. (line 26 of hyperlink.js)

It is now recommended to use getDerivedStateFromProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by ObidosDev** [comment]
or componentDidUpdate

**Comment by clickclickonsal** [comment]
Any updates on this? I'm happy to jump in on the PR if needed. :-)

**Comment by obipawan** [comment]
Fixed with (#29). [v0.0.17](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.17)
