### ISSUE TITLE
Tapping anywhere in original Text component triggers link

### ISSUE THREAD

**Issue by chrismllr** [obipawan/react-native-hyperlink#28]
Tapping anywhere within the Text will trigger an onPress (in the below example).

It seems the last link declared in the passed Text component will be used when tapping anywhere. Video attached.

```jsx
<Hyperlink 
  linkStyle={styles.linkStyles} 
  onPress={(url, text) => alert(`${url} -> ${text}`)}
>
  <View>
    <Text>{meeting.body}</Text>
  </View>
</Hyperlink>
```

### Versions
```
"react": "16.3.0-alpha.1",
"react-native": "0.54.0",
"react-native-hyperlink": "^0.0.13"
```
![hyperlinks-multiple](https://user-images.githubusercontent.com/9942917/39274106-8f865656-48a6-11e8-8d65-20ce63d1d7fc.gif)

**Comment by landonalder** [comment]
I can reproduce this with react-native 0.53 and react-native-hyperlink 0.0.13

**Comment by Cederman** [comment]
Happens for me as well in 0.0.13

**Comment by obipawan** [comment]
Thanks for reporting folks. It seems that the last release went in with a regression bug.
I've added a fix for it and is available in [v0.0.14](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.14)
Could you please try it out and let me know if this fixed the issue for you?

I'll be available to fix anything further asap.

**Comment by landonalder** [comment]
Appreciate the quick fix! Everything appears to be working fine for me on 0.0.14

**Comment by chrismllr** [comment]
@obipawan Thank you so much for the quick turnaround! `0.0.14` fixes the issue.
