### ISSUE TITLE
onHover for RN Windows

### ISSUE THREAD

**Issue by achipa** [obipawan/react-native-hyperlink#31]
I've been playing with react-native-hyperlink on windows (as in react-native-windows), and one of the things I miss is an onHover handler. I understand this might not be interesting on platforms without pointers, but would you take a PR to add this if it's behind a platform selector?

**Comment by obipawan** [comment]
Would this also apply to react native web?

**Comment by achipa** [comment]
Yes, the principle (mouse event handling) should be the same, minor syntax differences notwithstanding.

**Comment by obipawan** [comment]
Closing as abandoned
