### ISSUE TITLE
Error thrown on null children

### ISSUE THREAD

**Issue by pierre-elie** [obipawan/react-native-hyperlink#36]
Consider the following where `subtitle` can be null/undefined, in which case we do not add a `<Text>` element for it:

```jsx
<Hyperlink>
  <Text>{title}</Text>
  {subtitle && <Text>{subtitle}</Text>}
</Hyperlink>
```

This causes Hyperlink to throw en error `Cannot read property 'type' of null`.

I think this comes from the method parsing children, there is no safe-guard against null/undefined:

https://github.com/obipawan/react-native-hyperlink/blob/8cf43183bbd53ed28a03791eec7601da1d245626/src/Hyperlink.js#L121

**Comment by obipawan** [comment]
Thanks for reporting @pierre-elie.
This took a lot of time for my attention, but I've been able to get the fix out in [v0.0.16](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.16)
