### ISSUE TITLE
Wrong parsing of link

### ISSUE THREAD

**Issue by ObidosDev** [obipawan/react-native-hyperlink#37]
https://finance.liga.net/bank/novosti/privatbank-planiruet-spisat-300-tysyach-kreditov---smi

<img width="370" alt="screen shot 2018-11-06 at 15 39 28" src="https://user-images.githubusercontent.com/16224235/48067943-2d10dc80-e1da-11e8-89df-be126d0e95a3.png">

**Comment by obipawan** [comment]
I'm sorry I don't understand. Could you please use google translate to post the issue in English?

**Comment by ObidosDev** [comment]
Hi @obipawan sorry for missing description. There just a screenshot where I show how link have been parsed. There last part (---smi) have been lost. 
Do not try to read it, just look at the resulting link (blue one)

**Comment by obipawan** [comment]
Fixed in [v0.0.16](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.16)
