### ISSUE TITLE
Does not work for phone number 

### ISSUE THREAD

**Issue by Ayyagaries** [obipawan/react-native-hyperlink#38]
```
emailLink = () => (
    <Hyperlink
      onPress={this.emailCompany}
      linkText="FacilitySupport@IntelliCentrics.com"
      linkStyle={{ color: "#2980b9" }}
    >
      <Label style={[styles.tabletStyleWithMarginTop]}>
        Email: FacilitySupport@Int.com
      </Label>
    </Hyperlink>
  );

  phoneLink = () => (
    <Hyperlink
      onPress={this.callCompany}
      linkText="817-INT(732-3883)"
      linkStyle={{ color: "#2980b9" }}
    >
      <Label style={[styles.tabletStyleWithMarginTop]}>
        Phone: 817-INT(732-3883) , Select Option 2
      </Label>
    </Hyperlink>
  );

```

This is how I am calling it in my code 

```
{this.phoneLink()}
 {this.emailLink()}
```

The email works but the phone number does not show the link.

**Comment by danielsGit** [comment]
Same issue on my side. Do you have any solution @Ayyagaries ?

**Comment by obipawan** [comment]
I doubt [linkify](https://github.com/markdown-it/linkify-it) supports detecting phone numbers. But you're free to try creating a pattern for detection. Please have a look at  [linkify's](https://github.com/markdown-it/linkify-it) [docs](http://markdown-it.github.io/linkify-it/doc/) to customize linkify as per your needs. Make sure you pass the linkify object as a prop to Hyperlink under prop `linkify`

**Comment by anniewey** [comment]
@obipawan do u minds sharing an example? i've been checking the docs but not able to work it out. do we use `.add`?

my use case is to check against toll free num, such as `1300 111 1234` or `1300 22 1234`.
I have the [regex](https://stackoverflow.com/a/61788732/6210242) but dont know how to write the linkify.

**Comment by jtvargas** [comment]
@anniewey Hi! I was facing some issues too, and I add a new object in the linkify prop (it needs to be a linkify-it object schema)

- Install  [linkify-it](https://github.com/markdown-it/linkify-it)
- In your code declare initialize the linkify object (outside the component function). Like this
```
const linkify = linkifyIt();

// Add a custom rule for phone numbers
linkify.add('tel:', {
  validate(text, pos, self) {
    const tail = text.slice(pos);

    // Basic pattern to match phone numbers, adjust as needed
    const phonePattern = /^\+?[0-9\-\(\)\s]{10,15}/;
    if (!phonePattern.test(tail)) {
      return 0;
    }

    const match = tail.match(phonePattern);
    if (match) {
      return match[0].length; // Return the length of the matched pattern
    }

    return 0; // No valid phone number found
  },
  normalize(match) {
    // Normalize the matched text, e.g., removing spaces, dashes, etc.
    match.url = `${match.text.replace(/[^\d\+]/g, '')}`;
  },
});
```
- Add the new linkify prop `linkify={linkify}`

I also added some extra stuff in my onPress handler for the hyperlink (I only need to support phone and website)
```
  const handleOnPressHyperlink = async (textLink: string) => {
    const isPhoneLink = /^\d+$/.test(textLink);
    if (isPhoneLink) {
      // It's a phone number, initiate a call
      console.log(`Initiating call to ${textLink}`);
      return callNumber(textLink); // Ensure callNumber is correctly implemented to handle the call
    }
    console.log(`Opening URL: ${textLink}`);
    return Linking.openURL(textLink);
  };
  ```

**Comment by akashdeep0515** [comment]
@jtvargas it is not working for me, please help me. I may get fired if it doesn't
`import React, { useState, useRef, useEffect } from 'react';
import {
    StyleSheet,
    View,
    Text,
    TouchableOpacity,
    Modal,
    Dimensions,
    Image,
    ActivityIndicator,
    PermissionsAndroid,
    ToastAndroid,
    NativeModules,
} from 'react-native';
import ImageViewer from 'react-native-image-zoom-viewer';
import Constants from '../../shared/Constants';
import MessageSendState from '../../components/chatComponent/messageSendState';
import { getTime } from '../../helpers/getTime';
import RNFetchBlob from 'rn-fetch-blob';
import Icon from 'react-native-vector-icons/MaterialIcons';
import Hyperlink from '../../Hyperlink';
const LinkifyIt = require('linkify-it');

const linkify = LinkifyIt();

// Add a custom rule for phone numbers
linkify.add('tel:', {
  validate(text, pos, self) {
    const tail = text.slice(pos);

    // Basic pattern to match phone numbers, adjust as needed
    const phonePattern = /^\+?[0-9\-\(\)\s]{10,15}/;
    if (!phonePattern.test(tail)) {
      return 0;
    }

    const match = tail.match(phonePattern);
    if (match) {
      return match[0].length; // Return the length of the matched pattern
    }

    return 0; // No valid phone number found
  },
  normalize(match) {
    // Normalize the matched text, e.g., removing spaces, dashes, etc.
    match.url = `${match.text.replace(/[^\d\+]/g, '')}`;
  },
});
const fullWidth = Dimensions.get('window').width;
  
const Message = ({
    message,
    otherSender,
    isGroupChat,
    isSelected,
    groupMemberName,
    groupMemberImage,
}) => {
    const handleOnPressHyperlink = async (textLink) => {
        const isPhoneLink = /^\d+$/.test(textLink);
        if (isPhoneLink) {
          // It's a phone number, initiate a call
          console.log(`Initiating call to ${textLink}`);
          return callNumber(textLink); // Ensure callNumber is correctly implemented to handle the call
        }
        console.log(`Opening URL: ${textLink}`);
        return Linking.openURL(textLink);
      };
    const [isImageModal, setIsImageModal] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [isLoadingImage, setIsLoadingImage] = useState(false);
    const [messageText, setMessageText] = useState('')

    const handleImageModal = (imageUrl = '') => {
        imageUrl ? setIsImageModal(true) : setIsImageModal(false);
    };
    const checkPhoneNumber =()=>{
        const messageArray = message.body.split(' ')
        const newMessage = []
        messageArray.forEach(text => {
        const match = text.match(regex);
        if (match) {
          newMessage.push(`tel:${text}`)
        } else {
            newMessage.push(text)
        }
      })
      setMessageText(newMessage.join(' '))
    }
    const openFileViewer = () => {
        let commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
        commonToast.showWithGravity(
            'Downloading file...',
            ToastAndroid.LONG,
            ToastAndroid.BOTTOM,
        );
        const { attachment } = message;
        let fileUrl = attachment[0]?.url;
        let extension;
        if (attachment[0].hasOwnProperty('name')) {
            extension = attachment[0]?.name.split('.').pop();
        } else {
            extension = attachment[0]?.id.split('.').pop();
        }
        if (fileUrl && extension)
            chatFileDownload(fileUrl, extension, attachment[0].name);
        else {
            let commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
            commonToast.showWithGravity(
                'Incorrect file url',
                ToastAndroid.LONG,
                ToastAndroid.BOTTOM,
            );
        }
    };
    const chatFileDownload = (url, extension, name) => {
        if (Platform.OS === 'ios') {
            downloadFile(url);
        } else {
            try {
                PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                    {
                        title: 'storage permission required',
                        message: 'please provide the storage permission',
                    },
                ).then(granted => {
                    if (
                        granted === PermissionsAndroid.RESULTS.GRANTED ||
                        granted === 'never_ask_again'
                    ) {
                        //Once user grant the permission start downloading
                        downloadFileInAndroid(url, extension, name);
                    } else {
                        //If permission denied then show alert 'Storage Permission Not Granted'
                        let commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
                        commonToast.showWithGravity(
                            'require storage permission',
                            ToastAndroid.LONG,
                            ToastAndroid.BOTTOM,
                        );
                    }
                });
            } catch (err) {
                //To handle permission related issue
                let commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
                commonToast.showWithGravity(
                    'Require permission',
                    ToastAndroid.LONG,
                    ToastAndroid.BOTTOM,
                );
            }
        }
    };
    const downloadFileInAndroid = async (url, extension, name) => {
        const { config, fs } = RNFetchBlob;
        let DownloadDir = fs.dirs.DownloadDir;
        let downloadPath = DownloadDir + `/${name}`;
        let options = {
            fileCache: true,
            addAndroidDownloads: {
                useDownloadManager: true,
                notification: true,
                path: downloadPath,
                description: 'kreedo file',
            },
        };
        await config(options)
            .fetch('GET', url)
            .then(res => {
                let commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
                commonToast.showWithGravity(
                    'File downloaded',
                    ToastAndroid.LONG,
                    ToastAndroid.BOTTOM,
                );
            })
            .catch(e => {
                const commonToast = Platform.OS === 'android' ? ToastAndroid : Toast;
                commonToast.showWithGravity(
                    'Error while downloading file',
                    ToastAndroid.LONG,
                    ToastAndroid.BOTTOM,
                );
            });
    };

    const formatSize = sizeInBytes => {
        const sizeInKB = sizeInBytes / 1024;
        const sizeInMB = sizeInBytes / (1024 * 1024);

        return sizeInMB < 1
            ? `${sizeInKB.toFixed(2)} KB`
            : `${sizeInMB.toFixed(2)} MB`;
    };

    const renderAttachment = (attachment, messageBackgroundColor) => {
        if (attachment[0].type == 'image/jpeg' || attachment[0].type == 'photo') {
            return renderImageAttachment(messageBackgroundColor);
        } else if (
            attachment[0].type == 'video/mp4' ||
            attachment[0].type == 'video'
        ) {
            return renderVideoAttachment(messageBackgroundColor, attachment);
        } else if (attachment[0].type == 'mp3' || attachment[0].type == 'audio') {
            return renderAudioAttachment(messageBackgroundColor);
        } else {
            return renderFiles(messageBackgroundColor, attachment);
        }
    };

    const renderFiles = (messageBackgroundColor, attachment) => {
        const { date_sent, send_state } = message;
        const size = attachment[0].size;
        let name = attachment[0]?.name;
        let fileExtension;
        try {
            fileExtension = name.split('.').pop().toUpperCase();
        } catch {
            fileExtension = attachment[0]?.id.split('.').pop().toUpperCase();
            name = attachment[0]?.id;
        }
        const displayFileName =
            name?.length > 20 ? name?.substring(0, 20) + '...' : name;
        const getFileIcon = () => {
            const fileIcons = {
                HTML: Constants?.assets?.htmlIcon,
                PDF: Constants?.assets?.pdfIcon,
                PPT: Constants?.assets?.pptIcon,
                CSV: Constants?.assets?.csvIcon,
                DOC: Constants?.assets?.docIcon,
                DOCX: Constants?.assets?.docxIcon,
                XLS: Constants?.assets?.xlsIcon,
                XLSX: Constants?.assets?.xlsxIcon,
                XML: Constants?.assets?.xmlIcon,
                TXT: Constants?.assets?.txtIcon,
                PPTX: Constants?.assets?.pptxIcon,
            };
            return fileIcons[fileExtension] || Constants?.assets?.otherIcon;
        };
        return (
            <View
                style={[
                    styles.attachmentContainer,
                    {
                        backgroundColor: isSelected ? '#E5E4E2' : messageBackgroundColor,
                        borderTopRightRadius: otherSender ? 20 : 0,
                        borderTopLeftRadius: otherSender ? 0 : 20,
                    },
                ]}>
                <Modal visible={isLoading} transparent>
                    <View style={styles.modalContainer}>
                        {isLoading && (
                            <View style={styles.loaderContainer}>
                                <ActivityIndicator size="large" color="#fff" />
                            </View>
                        )}
                    </View>
                </Modal>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                    <TouchableOpacity onPress={openFileViewer}>
                        <View style={styles.attachmentTextContainer}>
                            <Image source={getFileIcon()} style={styles.attachmentIcon} />
                            <View style={{ marginLeft: 10 }}>
                                <Text style={styles.attachmentFileName}>{displayFileName}</Text>
                                <Text style={styles.fileExtension}>
                                    {fileExtension}
                                    {' \u00B7 '}
                                    {formatSize(size)}
                                </Text>
                            </View>
                        </View>
                    </TouchableOpacity>
                    <TouchableOpacity
                        onPress={openFileViewer}
                        style={styles.downloadButton}>
                        <Image
                            source={Constants?.assets?.chatDownload}
                            style={{
                                height: 25,
                                width: 25,
                                tintColor: 'white',
                            }}
                        />
                    </TouchableOpacity>
                </View>
                <View style={styles.dateSeenContainer}>
                    <Text style={styles.dateSent}>{getTime(date_sent, true)}</Text>
                    {otherSender ? '' : <MessageSendState send_state={send_state} />}
                </View>
            </View>
        );
    };

    const renderImageAttachment = messageBackgroundColor => {
        const { attachment, date_sent, send_state } = message;
        const fileSize = formatSize(attachment[0]?.size);
        try {
            extension = attachment[0]?.name.split('.').pop();
        } catch {
            try {
                extension = attachment[0]?.id.split('.').pop();
            } catch {
                extension = 'jpg';
            }
        }
        return (
            <View
                style={{
                    paddingBottom: 5,
                    paddingHorizontal: 2,
                    paddingTop: 2,
                    borderRadius: 5,
                    borderTopRightRadius: otherSender ? 20 : 0,
                    borderTopLeftRadius: otherSender ? 0 : 20,
                    minHeight: 10,
                    backgroundColor: isSelected ? '#E5E4E2' : messageBackgroundColor,
                }}>
                <TouchableOpacity
                    onPress={() => handleImageModal(attachment[0].url)}
                    style={styles.imageContainer}>
                    {isLoadingImage && (
                        <ActivityIndicator
                            style={{ width: '100%', height: '100%' }}
                            size="large"
                            color="#fff"
                        />
                    )}
                    <Image
                        onLoadStart={() => setIsLoadingImage(true)}
                        onLoadEnd={() => setIsLoadingImage(false)}
                        source={{ uri: attachment[0].url }}
                        style={styles.fullSizeImage}
                    />
                    <Text style={{ fontSize: 10, padding: 5, paddingLeft: 10 }}>
                        {fileSize != NaN && fileSize}
                        {' \u00B7 '}
                        {extension}
                    </Text>
                    {isImageModal && (
                        <Modal
                            visible={isImageModal}
                            transparent={true}
                            onRequestClose={() => {
                                handleImageModal(false);
                            }}>
                            <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.75)' }}>
                                <Icon
                                    name={'close'}
                                    size={Constants.Responsive.widthPx(10)}
                                    color="white"
                                    style={{
                                        alignSelf: 'flex-end',
                                        marginRight: Constants.Responsive.widthPx(3),
                                    }}
                                    onPress={() => handleImageModal(false)}
                                />

                                <ImageViewer
                                    imageUrls={[{ url: attachment[0].url }]}
                                    onCancel={() => setIsImageModal(false)}
                                    enableSwipeDown
                                    backgroundColor="transparent"
                                />
                                <TouchableOpacity
                                    onPress={openFileViewer}
                                    style={styles.imageModalDownloadButton}>
                                    <Image
                                        source={Constants?.assets?.chatDownload}
                                        style={{
                                            height: Constants.Responsive.widthPx(8),
                                            width: Constants.Responsive.widthPx(8),
                                            tintColor: 'white',
                                        }}
                                    />
                                </TouchableOpacity>
                            </View>
                        </Modal>
                    )}
                    <View style={[styles.dateSeenContainer, { marginTop: 0 }]}>
                        <Text style={styles.dateSent}>{getTime(date_sent, true)}</Text>
                        {otherSender ? '' : <MessageSendState send_state={send_state} />}
                    </View>
                </TouchableOpacity>
            </View>
        );
    };

    const renderVideoAttachment = (messageBackgroundColor, attachment) => {
        const { date_sent, send_state } = message;
        let attachmentFileName;
        try {
            attachmentFileName = attachment[0]?.name;
        } catch {
            attachmentFileName = attachment[0]?.id;
        }
        const displayFileName = attachmentFileName
            ? attachmentFileName.length > 20
                ? attachmentFileName.substring(0, 20) + '...'
                : attachmentFileName
            : 'video.mp4';
        const fileSize = formatSize(attachment[0]?.size);
        const fileExtension = attachmentFileName?.split('.').pop();
        return (
            <View
                style={[
                    styles.attachmentContainer,
                    {
                        backgroundColor: messageBackgroundColor,
                        borderTopRightRadius: otherSender ? 20 : 0,
                        borderTopLeftRadius: otherSender ? 0 : 20,
                    },
                    isSelected && { backgroundColor: '#E5E4E2' },
                ]}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                    <View style={styles.attachmentTextContainer}>
                        <Image
                            source={Constants?.assets?.videoIcon}
                            style={styles.attachmentIcon}
                        />
                        <View style={{ marginLeft: 10 }}>
                            <Text style={styles.attachmentFileName}>{displayFileName}</Text>
                            <Text style={styles.fileExtension}>
                                {fileExtension}
                                {' \u00B7 '}
                                {fileSize}
                            </Text>
                        </View>
                    </View>
                    <TouchableOpacity
                        style={styles.downloadButton}
                        onPress={openFileViewer}>
                        <Image
                            source={Constants?.assets?.chatDownload}
                            style={{
                                height: 25,
                                width: 25,
                                tintColor: 'white',
                            }}
                        />
                    </TouchableOpacity>
                </View>

                <View style={styles.dateSeenContainer}>
                    <Text style={styles.dateSent}>{getTime(date_sent, true)}</Text>
                    {otherSender ? '' : <MessageSendState send_state={send_state} />}
                </View>
            </View>
        );
    };

    const renderAudioAttachment = messageBackgroundColor => {
        const { attachment, date_sent, send_state } = message;

        const attachmentFileName = attachment[0]?.name;
        const displayFileName =
            attachmentFileName.length > 20
                ? attachmentFileName.substring(0, 10) + '...'
                : attachmentFileName;
        const fileExtension = attachmentFileName.split('.').pop();
        const fileSize = formatSize(attachment[0]?.size);

        return (
            <View
                style={[
                    styles.attachmentContainer,
                    {
                        backgroundColor: messageBackgroundColor,
                        borderTopRightRadius: otherSender ? 20 : 0,
                        borderTopLeftRadius: otherSender ? 0 : 20,
                    },
                    isSelected && { backgroundColor: '#E5E4E2' },
                ]}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                    <View style={styles.attachmentTextContainer}>
                        <Image
                            source={Constants?.assets?.audioIcon}
                            style={styles.attachmentIcon}
                        />
                        <View style={{ marginLeft: 10 }}>
                            <Text style={styles.attachmentFileName}>{displayFileName}</Text>
                            <Text style={styles.fileExtension}>
                                {fileExtension}
                                {' \u00B7 '}
                                {fileSize}
                            </Text>
                        </View>
                    </View>
                    <TouchableOpacity
                        style={styles.downloadButton}
                        onPress={openFileViewer}>
                        <Image
                            source={Constants?.assets?.chatDownload}
                            style={{
                                height: 25,
                                width: 25,
                                tintColor: 'white',
                            }}
                        />
                    </TouchableOpacity>
                </View>

                <View style={styles.dateSeenContainer}>
                    <Text style={styles.dateSent}>{getTime(date_sent, true)}</Text>
                    {otherSender ? '' : <MessageSendState send_state={send_state} />}
                </View>
            </View>
        );
    };
    return (
        <View>
            {otherSender ? (
                <View>
                    {isGroupChat && (
                        <View style={styles.othersMessageContainer}>
                            <View style={{ width: 50, height: 50 }}>
                                <Image
                                    source={
                                        groupMemberImage
                                            ? { uri: groupMemberImage }
                                            : Constants.assets.contactIcon
                                    }
                                    style={styles.profileimageStyle}
                                />
                            </View>
                            <Text style={styles.senderNameText} numberOfLines={1}>
                                {groupMemberName}
                            </Text>
                        </View>
                    )}

                    <View
                        style={[
                            styles.container,
                            styles.positionToLeft,
                            isGroupChat
                                ? {
                                    marginLeft: Constants.Responsive.widthPx(10),
                                }
                                : { marginVertical: 2 },
                        ]}>
                        <View>
                            {message?.attachment && message.attachment.length > 0 ? (
                                <View>{renderAttachment(message?.attachment, '#F6F6F6')}</View>
                            ) : (
                                <View
                                    style={[
                                        styles.message,
                                        styles.messageToLeft,
                                        { borderTopRightRadius: 20, borderTopLeftRadius: 0 },
                                    ]}>
                                    <Hyperlink onPress={handleOnPressHyperlink} linkify={linkify} linkDefault={true} linkStyle={{ color: '#2980b9', fontSize: 12 }}>
                                        <Text
                                            style={[
                                                styles.messageText,
                                                styles.textBlack,
                                                otherSender ? styles.selfToLeft : styles.selfToRight,
                                            ]}>
                                            {message.body || message.message || ' '}
                                        </Text>
                                    </Hyperlink>
                                    <View style={styles.downloadIconContainer}>
                                        <Text style={styles.dateSent}>
                                            {getTime(message.date_sent, true)}
                                        </Text>
                                    </View>
                                </View>
                            )}
                        </View>
                    </View>
                </View>
            ) : (
                <View style={[styles.container, styles.positionToRight]}>
                    <View>
                        {message?.attachment ? (
                            <View>{renderAttachment(message?.attachment, '#E3EFFD')}</View>
                        ) : (
                            <View
                                style={[
                                    styles.message,
                                    styles.messageToRight,
                                    { borderTopRightRadius: 0, borderTopLeftRadius: 20 },
                                    isSelected && { backgroundColor: '#E5E4E2' },
                                ]}>
                                <Hyperlink linkify={linkify} linkDefault={true} linkStyle={{ color: '#2980b9', fontSize: 12 }}>
                                    <Text
                                        style={[
                                            styles.messageText,
                                            styles.textBlack,
                                            styles.selfToRight,
                                        ]}>
                                        {message.body || message.message || ' '}
                                    </Text>
                                </Hyperlink>
                                <View style={styles.downloadIconContainer}>
                                    <Text style={styles.dateSent}>
                                        {getTime(message.date_sent, true)}
                                    </Text>
                                    <MessageSendState send_state={message.send_state} />
                                </View>
                            </View>
                        )}
                    </View>
                </View>
            )}
        </View>
    );
};
const styles = StyleSheet.create({
    dateSeenContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: 2,
    },
    loader: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginLeft: -20, // Adjust loader position
        marginTop: -15, // Adjust loader position
    },
    container: {
        position: 'relative',
        paddingHorizontal: 25,
        flexDirection: 'row',
        alignItems: 'flex-end',
    },
    positionToLeft: {
        justifyContent: 'flex-start',
    },
    positionToRight: {
        justifyContent: 'flex-end',
    },
    message: {
        maxWidth: fullWidth - 120,
        padding: 10,
        borderRadius: 10,
    },
    messageToLeft: {
        backgroundColor: '#F6F6F6',
    },
    messageToRight: {
        backgroundColor: '#E3EFFD',
    },
    messageText: {
        fontSize: 12,
    },
    textBlack: {
        color: 'black',
    },
    selfToLeft: {
        alignSelf: 'flex-start',
    },
    selfToRight: {
        alignSelf: 'flex-end',
    },
    dateSent: {
        fontSize: 8,
        color: Constants.colors.gray74,
        alignSelf: 'flex-end',
        marginRight: 5,
    },
    downloadButton: {
        backgroundColor: '#11A89C',
        borderRadius: 50,
        padding: 5,
        marginLeft: 15,
    },
    attachmentContainer: {
        marginVertical: 3,
        padding: 10,
        borderRadius: 20,
        height: 'auto',
    },
    attachmentFileName: {
        fontSize: 14,
        color: '#000000',
        marginBottom: 4,
        fontWeight: 'bold',
    },
    downloadIconContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: 6,
    },
    imageContainer: {
        width: '100%',
        aspectRatio: 1,
        borderRadius: 5,
        overflow: 'hidden',
        maxWidth: fullWidth - 120,
    },
    fullSizeImage: {
        flex: 1,
        resizeMode: 'contain',
        borderRadius: 1,
    },
    image: {
        flex: 1,
        resizeMode: 'cover',
    },
    attachmentTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachmentIcon: {
        width: 40,
        height: 40,
    },
    fileExtension: {
        fontSize: 10,
        color: '#777',
    },
    downloadIcon: {
        height: 25,
        width: 25,
        marginLeft: 10,
    },
    profileimageStyle: {
        height: 40,
        width: 40,
        resizeMode: 'cover',
        borderRadius: 50,
    },
    othersMessageContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: fullWidth - 120,
        paddingHorizontal: 10,
    },
    senderNameText: {
        color: Constants.colors.kreedoDarkBlueColor,
        fontSize: 13,
        fontWeight: 'bold',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    imageModalDownloadButton: {
        width: Constants.Responsive.widthPx(11),
        height: Constants.Responsive.widthPx(11),
        alignSelf: 'flex-end',
        marginTop: Constants.Responsive.widthPx(2),
        marginBottom: Constants.Responsive.widthPx(5),
        marginRight: Constants.Responsive.widthPx(10),
        backgroundColor: '#11A89C',
        borderRadius: Constants.Responsive.widthPx(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default Message;
`
