### ISSUE TITLE
Emails not working on Android devices

### ISSUE THREAD

**Issue by brendandestefano** [obipawan/react-native-hyperlink#39]
**Describe the bug**
Tapping on mailto links on Android device is not opening mail apps. Working fine on iOS devices.

**To Reproduce**
1. Click on mailto:someemail@email.com
2. See blank screen

**Expected behavior**
Open default mail app or show mail app choices

**Screenshots**
![Screenshot_20190416-110528](https://user-images.githubusercontent.com/18404323/56221298-ffa54600-6037-11e9-9418-7a53023ce49f.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android Version 9
 - Browser: Default
 - Version: react-native-hyperlink 0.0.14

**Comment by alburdette619** [comment]
I'm seeing this on iOS with `linkDefault` as well.  It does nothing.

**Comment by alburdette619** [comment]
Setting the following props worked for me on both platforms;

```javascript
    onPress={url => Linking.openURL(url)}
    linkText={url =>
      url.includes('mailto:') ? url.replace('mailto:', '') : url
    }
```
