### ISSUE TITLE
How to fix the url prefix wrapped ?

### ISSUE THREAD

**Issue by Github-Player** [obipawan/react-native-hyperlink#4]
In the end of one line, the 'http://' url prefix wrapped. 
how to fix the if one line not enough to show url, wrap to new line to show the full url ?

example : 

xxxxx http://
github.com

to 

xxxxx
http://github.com

**Comment by obipawan** [comment]
does your render function look something like this ?

```javascript
render(){
     return (
          <Hyperlink ...>
             <Text ...>xxxxx http://</Text>
             <Text ...>github.com</Text>
          </Hyperlink>
     )
}

**Comment by tommychoo** [comment]
No,  i just append this format
`
<Text>xxxxxx</Text>
<Text>Full link (http://github.com)</Text>
<Text>xxxxxxx</Text>
`
Are you tried this and get this problem ? because your preview image also has this issue

**Comment by obipawan** [comment]
@tommychoo first off, I apologise for the delay, been really busy :(
The wrapping would happen as it would with a regular `<Text/>` component. Have you tried by only setting an empty `onPress` prop like `onPress={() => {}}` and not the `linkStyle` prop in the `Hyperlink` component  and then with only `<Text />`? It would most likely look the same. Example below

```javascript
render(){
    return(
        <Hyperlink onPress={()=>{}}>
            xxxxxx https://github.com/obipawan/react-native-hyperlink/issues/4 xxxxxxx
        </Hyperlink>
    )
}
```
Vs 

```javascript
render(){
    return(
        <Text>
            xxxxxx https://github.com/obipawan/react-native-hyperlink/issues/4 xxxxxxx
        </Text>
    )
}
```
* notice that I haven't specified the `linkStyle` prop.

Both of these would look exactly the same.
If you still have this problem, then please share me a gist your component that I can reproduce and i'll gladly have a look at the problem :)

I did try rendering this with and without `Hyperlink` and they both look exactly the same.

<img width="377" alt="screen shot 2016-07-23 at 1 49 49 pm" src="https://cloud.githubusercontent.com/assets/5319269/17076936/81fe1cee-50dc-11e6-9696-3b26ddd61bd7.png">

cheers
