### ISSUE TITLE
VI swap file committed

### ISSUE THREAD

**Issue by mbaroukh** [obipawan/react-native-hyperlink#40]
Hi.

Maybe you should remove 
https://github.com/obipawan/react-native-hyperlink/blob/master/src/.Hyperlink.js.swp
from repository :)

**Comment by obipawan** [comment]
Thanks for reporting @mbaroukh  :)
Removed this in [v0.0.16](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.16)
