### ISSUE TITLE
Not linking custom domains

### ISSUE THREAD

**Issue by ETLopes** [obipawan/react-native-hyperlink#42]
**Describe the bug**
React-native-hyperlink is not linking custom urls. For example "www.trusst.app" does not get linked. 

**To Reproduce**
create a text within the Hyperlink tag with the text www.trusst.app

**Expected behavior**
The text should be clickable and formatted as designed.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/34959471/63195055-f8bf2c00-c047-11e9-8cf7-208f3b6991f9.png)

**Smartphone (please complete the following information):**
iOS(any)
Tested on iphone 6

**Additional context**

**Comment by obipawan** [comment]
Hi @ETLopes 
Thanks for reporting.
Hyperlink uses [linkify-it](https://github.com/markdown-it/linkify-it) to detect patterns.

You need to pass a custom linkify-it object like so,

```javascript
import { Text } from 'react-native'
import Hyperlink from 'react-native-hyperlink'

export default () =>
<Hyperlink
    onPress={ ... }  
    linkify={ require('linkify-it')().tlds('app', true) } // Add unofficial `.app` domain
>
    <Text>www.trusst.app</Text>
</Hyperlink>
```
