### ISSUE TITLE
Issues when hyperlink is nested

### ISSUE THREAD

**Issue by jjg77** [obipawan/react-native-hyperlink#47]
If the hyperlink component is nested under another touchable, both events fire.  First the parent touchable fires, then the hyperlink fires.   Anyway around this?

**Comment by obipawan** [comment]
This isn't really the library's issue. You'd expect the same behaviour with a regular `Text` component with an `onPress` prop. The following example demonstrates it.

```
<TouchableHighlight onPress={ () => alert('clicked on the parent touchable')}>
    <Text onPress={() => alert('clicked on text')}>This is some random text nested inside a Touchable</Text>
</TouchableHighlight>
```

This library in-fact breaks your text into multiple `<Text/>` components. My guess is, you'll have to reorder your jsx isolating the touchable.
