### ISSUE TITLE
Touchable opacity on link press in Android

### ISSUE THREAD

**Issue by vandervidi** [obipawan/react-native-hyperlink#5]
can you add this feature?

**Comment by obipawan** [comment]
Adding this would be simple enough, but as of now it inherently depends on the `<Text>` component to be capable of nesting regular `<View>`s. 
There's a PR for nesting Views in Text components
https://github.com/facebook/react-native/pull/8619 and it should hopefully be merged sometime soon. 
So with that, it would be possible to add this with a release which has this merged in react-native
cheers
