### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by filipegl** [obipawan/react-native-hyperlink#53]
**Is your feature request related to a problem? Please describe.**
I can't identify links through Text Input

**Describe the solution you'd like**
It would be amazing if it were possible to identify links through Text Input, just like Whatsapp

**Comment by mmkhmk** [comment]
It would be appreciated if TextInput is supported.
Thank you.

**Comment by obipawan** [comment]
No plans for TextInput at the moment.

**Comment by charlestbell** [comment]
+1 for textInput support

**Comment by charlestbell** [comment]
NVM, turns out it's built right into TextInput:

```
<TextInput editable={false} dataDetectoryTypes={'link'}
```

https://reactnative.dev/docs/textinput#datadetectortypes-ios

**Comment by MystDexter** [comment]
Thanks for the tip @charlestbell 
Has anyone figured out how to change the color of dataDetectorTypes links?
