### ISSUE TITLE
Non Safari default browser links do not work

### ISSUE THREAD

**Issue by iamgerardm** [obipawan/react-native-hyperlink#57]
If your default browser is set to something aside from Safari -- links do not open.

**To Reproduce**
1. Download Chrome and set it as a default browser
2. Tap a link

**Expected behavior**
Links open

**Smartphone (please complete the following information):**
 - OS: 14+ -- maybe lower

**Comment by cedancp** [comment]
Hello @iamgerardm 

After debugging the issue I found out that the "problem" was with Linking from RN returned not supported URL when the default browser is not Safari.

The solution for me was to configure my iOS app like this:

> add https & http to LSApplicationQueriesSchemes in Info.plist
> Originally posted by @andrzejbe in #https://github.com/facebook/react-native/issues/30133#issuecomment-705563026_

Hope this helps.

**Comment by debiff** [comment]
> Hello @iamgerardm
> 
> After debugging the issue I found out that the "problem" was with Linking from RN returned not supported URL when the default browser is not Safari.
> 
> The solution for me was to configure my iOS app like this:
> 
> > add https & http to LSApplicationQueriesSchemes in Info.plist
> > Originally posted by @andrzejbe in #[facebook/react-native#30133 (comment)](https://github.com/facebook/react-native/issues/30133#issuecomment-705563026)_
> 
> Hope this helps.

Can you share the snippet of info.plist to see how you add the suggested entry?

Regards

**Comment by cedancp** [comment]
> > Hello @iamgerardm
> > After debugging the issue I found out that the "problem" was with Linking from RN returned not supported URL when the default browser is not Safari.
> > The solution for me was to configure my iOS app like this:
> > > add https & http to LSApplicationQueriesSchemes in Info.plist
> > > Originally posted by @andrzejbe in #[facebook/react-native#30133 (comment)](https://github.com/facebook/react-native/issues/30133#issuecomment-705563026)_
> > 
> > 
> > Hope this helps.
> 
> Hello @cedancp
> 
> Can you share the snippet of info.plist to see how you add the suggested entry?
> 
> Regards

This is the key of info.plist where I added the schemes
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>https</string>
    <string>http</string>
</array>
```
