### ISSUE TITLE
When used on Web, error about prop types appear. 

### ISSUE THREAD

**Issue by Njaah-0** [obipawan/react-native-hyperlink#58]
**Describe the bug**
This error is given on Web:
Failed prop type: Hyperlink: prop type `linkStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.     in Hyperlink (created by _default)

This happens because Text.propTypes is no longer a thing in latest RNW.

**To Reproduce**
Try using this package with latest RNW.

**Expected behavior**
No error should be logged

**Additional info**
I patched this in my own project by simply doing this:
`linkStyle: _propTypes["default"].oneOfType([_propTypes["default"].object, _propTypes["default"].number]),`

**Comment by brandonpearcy** [comment]
I can confirm this patch works. 

1. Edit `node_modules/react-native-hyperlink/src/Hyperlink.js`
2. Replace `linkStyle: textPropTypes.style,` with `linkStyle: _propTypes["default"].oneOfType([_propTypes["default"].object, _propTypes["default"].number]),`
3. Make your patch persistent somehow, e.g. `npx patch-package react-native-hyperlink`

**Comment by obipawan** [comment]
the latest version [v0.0.22](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.22) has the fix with types.

**Comment by duggster** [comment]
Hi @obipawan do you know when v0.0.22 will be released?
