### ISSUE TITLE
Not detected hyper link in text

### ISSUE THREAD

**Issue by XoanTT** [obipawan/react-native-hyperlink#63]
I have some text detail to show and I won't show hyperlinks. 
this text's ok: 'this is link https://www.google.com.vn/'
but this text is not OK: 'this is linkhttps://www.google.com.vn/'
I think it can't be detected hyperlink when link not white space

**Comment by obipawan** [comment]
@XoanTT this package is built on top of [linkify-it](https://github.com/markdown-it/linkify-it) for parsing potential links. You'd have to build your own patterns as per the documentation of linkify-it to get custom links apart from the defaults that it understands.
