### ISSUE TITLE
Throwing error with react-native 0.69.3

### ISSUE THREAD

**Issue by ursnj** [obipawan/react-native-hyperlink#67]
**Describe the bug**

Warning: Failed prop type: Hyperlink: prop type `linkStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.
    at Hyperlink (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=njsolutions.watchpartys&modulesOnly=false&runModule=true:216800:22)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamblvck** [comment]
I'm experiencing exactly the same error, now running on Expo SDK 46 (`react-native@0.69.4`)

**Comment by karanmartian** [comment]
when will a release be made with the fix? looks like the PR is already done

**Comment by ursnj** [comment]
I dont think this is active , so i ahve fixed it in react-native-linkify library

**Comment by karanmartian** [comment]
@ursnj could you share the link to this link? cant find it - react-native-linkify

**Comment by ursnj** [comment]
https://www.npmjs.com/package/react-native-linkify

**Comment by karanmartian** [comment]
@ursnj you are still using const textPropTypes = Text.propTypes || {} in that source at the new repo if I am not mistaken. This would throw the same error. It should be TextPropTypes right?

**Comment by tomwaitforitmy** [comment]
@karanmartian did you try @ursnj package? Solved the issue for me 👌. It would prefer a fix to this repo here, but if it is not active what can we do?

**Comment by obipawan** [comment]
hey folks, fixed in [0.0.21](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.21). Let me know if this works.

**Comment by sandergo90** [comment]
@obipawan this new release is giving typescript issues.

`import Hyperlink JSX element type 'Hyperlink' does not have any construct or call signatures`.

**Comment by obipawan** [comment]
Oh crap i messed up the export! I'll fix this in an hour, I'm outside without my machine. In the meanwhile you can  `import {Hyperlink} from 'react-native-hyperlink'.

**Comment by obipawan** [comment]
@sandergo90 updated with [v0.0.22](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.22). Hope this works 🤞

**Comment by sandergo90** [comment]
Works like a charm, thanks 👌
