### ISSUE TITLE
If no onButtonPress, default to just calling Linking.openURL()

### ISSUE THREAD

**Issue by chuckhacker** [obipawan/react-native-hyperlink#9]
Why doesn't a URL hyperlink library open a URL by default if there's no special callback overriding the behavior? Doesn't make sense to me.

**Comment by obipawan** [comment]
hey @TheChuckster, I wasn't really aiming for this library to have a default at the time of building this. You do have a point and I agree 👍, I'll be happy to accept a PR for this

**Comment by TheChuckster** [comment]
Ah, the only caveat is that on iOS you have to pull in a native module to use Linking:
https://facebook.github.io/react-native/docs/linking.html

**Comment by jakecraige** [comment]
I think you'd only need to do that if you wanted to handle app open URLs, not for opening a URL

**Comment by obipawan** [comment]
Added support for [Linking](https://facebook.github.io/react-native/docs/linking.html). By default, the behaviour won't kick in, so you'll have to set the `linkDefault` prop to let the platform take over if the `onPress` prop isn't specified.

Available in [0.0.10](https://github.com/obipawan/react-native-hyperlink/releases/tag/v0.0.10)
